### ISSUE TITLE
Ubuntu 15.10 64-bit deb package not working

### ISSUE THREAD

**Issue by Byteschmiede** [bill-auger/av-caster#27]
I tried both installing from deb package and compiling from source. Everytime while starting it said something like segfaulting without stack trace

**Comment by bill-auger** [comment]
could you give me more information about your OS - like the output of:

```
uname -a
gst-launch-1.0 --version
```

the debug build will print much useful information - could you try compiling the debug version like:

```
  cd Builds/GnuMakefile
  make
  ./build/av-caster-dbg
```

if you are on LCTV? feel free to come into my channel and i can help you in real-time https://www.livecoding.tv/bill-auger/ - also i have just setup a gitter chat https://gitter.im/bill-auger/av-caster

**Comment by bill-auger** [comment]
oh also if you are not on LCTV i have just setup a gitter chat https://gitter.im/bill-auger/av-caster

**Comment by Byteschmiede** [comment]
Linux laptop 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The debug version also not starting .. no stack trace 

I just followed you on LCTV :)

**Comment by bill-auger** [comment]
ok i was able to reproduce this on a fresh install of ubuntu 15.10 64bit

for me tho when i compiled it manually it ran properly - could you try again building the debug binary after installing all of the packages below

```
  sudo apt-get install build-essential libfreetype6-dev libgstreamer-plugins-base1.0-dev libx11-dev libxcursor-dev libxinerama-dev freeglut3 gstreamer1.0-plugins-bad gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly libfreetype6 libgl1-mesa-glx libx11-6 libxcomposite1 libxcursor1 libxext6 libxinerama1 libxrender1

  cd Builds/GnuMakefile
  make
  ./build/av-caster-dbg
```

**Comment by Byteschmiede** [comment]
These packages are already installed on my system ... still getting segfault error after building

**Comment by bill-auger** [comment]
@csNewscope 

i think the problem may be that the 64bit build needs to be built against gStreamer v1.6 and travis is using a much older version - i may actually need to raise the minimum requirement to gStreamer v1.6 (which for debian is sid and ubuntu is wily) and try to get travis to build against gStreamer v1.6 - so for now i will be deleting the 64bit deb packages

i really do not know why you are having trouble running your locally compiled binary tho - i have installed ubuntu 15.10 amd64 today on two different boxes and the av-caster compiled and ran successfully on both - i have uploaded a binary that i compiled on ubuntu 15.10 amd64 --> https://github.com/bill-auger/av-caster/releases/download/v0.15/av-caster-v0.15-amd64.tar - if this will not run for you there must be something specific to your setup that is preventing it

btw - you are not trying to run this in a VM are you ? av-caster will not run in a VM

**Comment by Byteschmiede** [comment]
I've tried your compiled version .. still not working.

No i'm not running that in a VM :/

**Comment by bill-auger** [comment]
the only caveats i can think of that i have not menrtioned are that i think that a sound card and ALSA are a strict requirement also and your xserver must support xv rendering
i could compile a debugging version for you to run in gdb - maybe without audio or video preview  - other than that i am running out of ideas

**Comment by bill-auger** [comment]
@csNewscope 
there is now a working 64bit deb package for ubuntu 15.10 a new repo if you would care to try that :)
http://software.opensuse.org/download/package?project=home:bill-auger&package=av-caster

**Comment by Byteschmiede** [comment]
Hey i downloaded the amd64 deb .. still not working.. Ubuntu showed me the stacktrace and i clicked on "Submit" maybe you get a message or something with informations

**Comment by Byteschmiede** [comment]
GDB Output:

Starting program: /home/desktop/Downloads/av-caster 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000004a70b1 in int juce::CharacterFunctions::compare<juce::CharPointer_UTF8, juce::CharPointer_UTF8>(juce::CharPointer_UTF8, juce::CharPointer_UTF8) ()

**Comment by ThomasBS** [comment]
Hi Bill. I'm having the same issues. I didnt want to create another issue if it's the same thing. Is it possible to provide some sort of `--debug` flag while av-caster is under development? I installed it fine from opensuse, but when I run `$ av-caster` (or any other command trying to start the program), there's a VERY quick window popping up, it closes and command line tells me there was an error code of 255 (?).

```
$ uname -a
Linux TBS 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ gst-launch-1.0 --version
GStreamer 1.6.0
https://launchpad.net/distros/ubuntu/+source/gstreamer1.0
```

**Comment by bill-auger** [comment]
@ThomasBS -

there are still some issues with the packaged versions - i should probably update these ASAP seeing as most ppl seem to prefer this install method - most errors now are related to hardware devices - if it is possible for you to compile from the current master branch i have added debugging traces to the release build and some feature switches

once you have av-caster v0.15.202 or later you should see some errors in red when running from the command line which may pinpoint the problem

also you can run `av-caster --help` to see some options under 'FEATURE SWITCHES' - the --no-media option will almost certainly allow the program to start but in an essentially useless state - try the others to see if you can get a usable configuration

**Comment by bill-auger** [comment]
the package in the [OBS repo](http://software.opensuse.org/download/package?project=home:bill-auger&package=av-caster) has been rebuilt and now corresponds to the current master branch and tag [v0.15.203](https://github.com/bill-auger/av-caster/releases/tag/v0.15.203)
