### ISSUE TITLE
Fails to compile in Fedora 23 x64

### ISSUE THREAD

**Issue by chazzbg** [bill-auger/av-caster#28]
When trying to compile av caster on Fedora 23 i encountered some errors . 
1. JuceHeader.h was not found 
make was complaining that it cant find JuceHeader.h . 

```
mkdir: missing operand
Try 'mkdir --help' for more information.
Makefile:108: recipe for target '/AvCaster_86a5e2ca.o' failed
make: [/AvCaster_86a5e2ca.o] Error 1 (ignored)
Compiling AvCaster.cpp
In file included from ../../Source/MainContent.h:27:0,
                 from ../../Source/AvCaster.h:25,
                 from ../../Source/AvCaster.cpp:20:
../../Source/Controls.h:24:24: fatal error: JuceHeader.h: No such file or directory
compilation terminated.
Makefile:108: recipe for target '/AvCaster_86a5e2ca.o' failed
make: *** [/AvCaster_86a5e2ca.o] Error 1

```

I added a relative path to the header file, in every header that  includes JuceHeader.h and the compilation continued BUT 
2. Even though i have both gstreamer1-devel and gstreamer1-plugins-base-devel , it complains that it cant find gst.h 

```
make CONFIG=RELEASE
mkdir: missing operand
Try 'mkdir --help' for more information.
Makefile:108: recipe for target '/AvCaster_86a5e2ca.o' failed
make: [/AvCaster_86a5e2ca.o] Error 1 (ignored)
Compiling AvCaster.cpp
In file included from ../../Source/AvCaster.cpp:21:0:
../../Source/Gstreamer.h:23:21: fatal error: gst/gst.h: No such file or directory
compilation terminated.
Makefile:108: recipe for target '/AvCaster_86a5e2ca.o' failed
make: *** [/AvCaster_86a5e2ca.o] Error 1
```

i'm starting to think that I did something wrong

**Comment by bill-auger** [comment]
sry @chazzbg - i could not reporoduce this - i installed fedora 23 today to build myself and note the exact dependencies but i had no problem at all - i did not need to adjust any header paths - i just installed some dependencies and it built smoothly

these are the packages i needed to install on a fresh install of fedora23 64-bit
build dependencies:

```
  sudo dnf install gcc-c++ libX11-devel freetype-devel libXinerama-devel libXcursor-devel gstreamer1-plugins-base-devel
```

runtime dependencies:

```
  sudo dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  sudo dnf install gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-ugly 
```

**Comment by chazzbg** [comment]
Lol,  so the problem is in my box.  I came to the conclusion that make could not resolve include paths well,  or just gcc cant pase them well. Never mind.

**Comment by bill-auger** [comment]
i would like to make rpm package someday - if you would like to test that let me know

thing is this program will not run in a virtual machine so i can test the build on a particular OS but i can not actually test the program unless i install each OS

**Comment by bill-auger** [comment]
@chazzbg 
there is now a rpm package repo for fedora 23 if you would care to try that :)
http://software.opensuse.org/download/package?project=home:bill-auger&package=av-caster

**Comment by chazzbg** [comment]
thanks! i've installed it, but there are some issues.
1. won't broadcast when livecoding server selected , ( broadcast key is set )
when i click broadcast button, the preview freezes 
2. when changing to RTMP and putting the whole server + key , it starts broadcasting but on livecoding i see just black screen and buzzing noises 

nothing is spit in the console as errors

**Comment by bill-auger** [comment]
the release version wont print anything - perhaps i could make a debug binary for you

the black screen thing maybe a glitch - you may want to try each of ALSA/PULSE/JACK audio - have you tried streaming more than once ? restarting av-caster in between attempts - also the settings do not take effect immediately - after changing any settings you must click the "save" button then close and restart the program at least once before using the new settings

did you install all of the packages i noted above? what is your output if you run this command -->

```
gst-launch-1.0 --version
```

i have tried installing fedora from two different isos but i have not yet been able to get either of them to boot - i tried also ScientificLinux but it looks like fedora and openSUSE are currently the only rpm based distros with gstreamer 1.6 available - im going to try installing openSUSE next but as for fedora i may need to find some alternate install method so i can test this on fedora myself

**Comment by chazzbg** [comment]
yes , i've restarted the application. 

> ╭─dilkov@InixWeb: ~  ‹php v5.6.15›
> ╰─○ gst-launch-0.10 --version
> gst-launch-0.10 version 0.10.36
> GStreamer 0.10.36
> http://download.fedoraproject.org

now I tried again, it broadcasted once. 
the results are kind of inconsistent 
sometimes it broadcasts , sometimes it won't ... 

does the error when closing the app can do any impact on the next launch ?

> (av-caster:14390): GStreamer-CRITICAL **: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed
> 
> (av-caster:14390): GStreamer-CRITICAL **: gst_object_unref: assertion '((GObject *) object)->ref_count > 0' failed

**Comment by bill-auger** [comment]
nope those errors are just a small memory leak but are not a critical problem - it seems that your main issue is that you have gstreamer 0.10 installed - gstreamer 0.10 is very old and deprecated - you could try uninstalling all gstreamer\* packages and replacing with their gstreamer1\* replacements - i would be hoping to see "GStreamer 1.6.1"

the rpm package should have pulled in the newer versions but it will not delete the old ones - they are technically different libraries - normally they can co-exist but maybe your system is mixing them up

**Comment by chazzbg** [comment]
i've done it. 
but the problem does not seem linked to that. 
i appears that when i set PULSE for audio source - it can't broadcast 
on alsa - broadcast with no sound 
JACK - av-caster does not start at all 

this may be will eliminate the problem with setting livecoding.tv as broadcast destination, that i said earlier. 

additionaly i've noticed that  when i change the broadcast destination ( file, rtmp server, livecoding.tv ) it resets all settings

**Comment by bill-auger** [comment]
as for the sound this depends if you have pulse or jack installed - alsa is the most standard - i suspect if you mess around in alsamixer you just need to enable your mic as the capture source

so what is your output now from this command -->

```
gst-launch-1.0 --version
```

**Comment by chazzbg** [comment]
i was always thinking that for the last 4-5 years, pulse became primary choice. 
and, i'm currently on my office descktop, and i don't have mic 

> ╰─○ gst-launch-1.0 --version
> gst-launch-1.0 version 1.6.1
> GStreamer 1.6.1

**Comment by bill-auger** [comment]
ok thats better - if youre still having issues tho were gonna have to get you a debugging version or i will need to get fedora installed somehow to see if i can reporduce your issue - do you have some spare disk space ? you could install one of the distros it is know to work on like debian, arch, or ubuntu - that could at least determine if your hardware is compatible - do you have another PC at home you could try it on ? either with fedora or whatever

sry i cant be more helpful now as this app is very new and you are the first one to have issues on fedora so there is little common experience yet to draw from

**Comment by bill-auger** [comment]
the latest version has more fine grained selection of media elements and verbose debugging
