### ISSUE TITLE
Missing libircclient?

### ISSUE THREAD

**Issue by seanc** [bill-auger/av-caster#48]
Install it like so:

``` shell
$ sudo apt-get install libircclient-dev
```

**Comment by bill-auger** [comment]
yes - libircclient-dev on deb-based distros - libircclient-devel on rpm-based distros - and libircclient on arch

unfortunately the headers install location is not consistent across platforms - if your compiler can not find the headers on your system you can:

```
sudo mkdir /usr/include/libircclient
sudo cp  /usr/include/libirc*  /usr/include/libircclient/
```

**Comment by bill-auger** [comment]
there is one other caveat with the current master commit - sry i did not know they were announcing it this week - i had planned not to have this one set so long

you will also want to open up Constants.h and change the values for PICTURES_DIR and VIDEOS_DIR on lines 174 and 175  to some existing directory under your home directory - any directory will do as long as it exists and is writable

**Comment by bill-auger** [comment]
just added -I /usr/include/libircclient for simplicity - no need for trickery

the issue with xdg dirs is fixed also
d0ad700844870a39e15715e6116038e6f04eec86
