### ISSUE TITLE
Fail building on Fedora 24

### ISSUE THREAD

**Issue by platedodev** [bill-auger/av-caster#57]
After running this script on Fedora 24:

```
### build dependencies ###
su -c "dnf install freetype-devel gcc-c++ gstreamer1-plugins-base-devel                \
             libircclient-devel libX11-devel libXinerama-devel libXcursor-devel"
### runtime dependencies (rpmfusion repositories) ###
RPMFUSION_URL=http://download1.rpmfusion.org
FEDORA_VERSION=24
REPO1_PKG=$RPMFUSION_URL/free/fedora/rpmfusion-free-release-24.noarch.rpm
REPO2_PKG=$RPMFUSION_URL/nonfree/fedora/rpmfusion-nonfree-release-24.noarch.rpm
su -c "dnf install $REPO1_PKG $REPO2_PKG"
su -c "dnf install gstreamer1-plugins-good gstreamer1-plugins-bad-free \
                gstreamer1-plugins-ugly libircclient1"
### compile ###
cd Builds/Makefile
make
su -c "make install"
### run ###
av-caster 
```

I'm getting this error:

> No package libircclient1 available.
> Error: Unable to find a match.
> Compiling juce_core.cpp
> Compiling juce_data_structures.cpp
> Compiling juce_events.cpp
> Compiling juce_graphics.cpp
> Compiling juce_gui_basics.cpp
> Linking AvCaster
> Password: 
> make: **\* No rule to make target 'install'.  Stop.
> ./make.sh: line 17: av-caster: command not found

**Comment by bill-auger** [comment]
sry - libircclient1 is a typo - libircclient is installed above along with libircclient-devel

im not sure what is happening with the install step but it appears that the binary has built successfully - it can be run from the Builds/Makefile/ dir like: `./build/av-caster`

**Comment by bill-auger** [comment]
i was able to compile and run on fedora24 - i had some runtime gStreamer errors but these were likely due to running in QEMU

i could not reproduce the install error tho - `make install` and `make uninstall` both worked as expected
