### ISSUE TITLE
Fedora 24 : compile from scratch

### ISSUE THREAD

**Issue by ghost** [bill-auger/av-caster#58]
Hello
after the installations of build dependencies, I have compiling the sources with the script for Fedora

> ### build dependencies
> 
> dnf install freetype-devel gcc-c++ gstreamer1-plugins-base-devel
> dnf install libircclient-devel libX11-devel libXinerama-devel libXcursor-devel

After a error during the compiling process, I had to install another package :

> dnf install libXrandr-devel

after a success compiling, when I want to launch the av-caster, I have this error message :

```
[ERROR]:   error creating 'jackaudiosrc' element 'audio-jack-source'
[ERROR]:   Error creating AudioBin GstElements.
[ERROR]:   Error initializing dynamic GstElements.

```

I don't know what this error is

for information, the _libircclient1_ doesn't exist. it's the _libircclient_ package.

**Comment by bill-auger** [comment]
@mathdatech 

please search existing issue before posting new ones - the previous issue to this one is also regarding fedora24 https://github.com/bill-auger/av-caster/issues/57 in which i already noted that libircclient1 is a typo

the OP of that issue did not mention libXrandr-devel tho - i have not yet built av-caster on fedora24 so i cant say any more at the moment - would you be so kind as to re-post this on the previous fedora24 #57 issue?
