### ISSUE TITLE
Can't able to see the titlebar

### ISSUE THREAD

**Issue by sonulohani** [bill-auger/av-caster#59]
I have a Dell laptop having 15 inch screen. However i am not able to see the titlebar of the AVCaster because of which i couldn't able to move the screen. Adding screenshot to give more info about this.
![avcaster](https://cloud.githubusercontent.com/assets/2958681/18412751/516693fa-77b4-11e6-84ac-269a595e7b30.png)

**Comment by bill-auger** [comment]
as stated on issue #31 - the target desktop resolution is 1280x800 - from the looks of your screenshot that is probably your resolution now but your your taskbars are covering the av-caster window - i think the entire window would fit on your screen if you set your top and bottom taskbars to auto-hide or move them to the sides

this is not a problem anyways as all of the controls are visible - you can shutdown av-caster with ALT-F4 or right-clicking it's tab on your bottom taskbar - if you really want to see the titlebar without hiding your taskbars then hold ALT key while click and dragging the mouse to move the window
