### ISSUE TITLE
Fedora 24 - Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by bidzapfc** [bill-auger/av-caster#60]
https://software.opensuse.org/download/package?project=home:bill-auger&package=av-caster

Used this to install it. It did install, there were no icon in start menu and running from terminal gave me "Illegal instruction (core dumped)"

**Comment by bill-auger** [comment]
aw that too bad - that was the first build for fedora 24 and i have not tested it yet - i will look into it tomorrow

**Comment by bill-auger** [comment]
i have confirmed the package is currently broken on fedora 24 and 23 also

av-caster does compile and run on both however

will keep this issue open until a resolution is found

**Comment by bidzapfc** [comment]
Great! Please notify me when it is on repo again, so I can test it

**Comment by bill-auger** [comment]
@bidzapfc -

i have resolved the issue with the fedora package - i do not have fedora installed but these do launch for me now in a VM

note that av-caster-0.16.004-6.1 is the broken package on fedora - the latest one is av-caster-0.16.004-6.2

**Comment by bidzapfc** [comment]
[ERROR]:   error creating 'jackaudiosrc' element 'audio-jack-source'
[ERROR]:   Error creating AudioBin GstElements.
[ERROR]:   Error initializing dynamic GstElements.

New build is giving this @bill-auger

**Comment by bill-auger** [comment]
ok that is much better but is a very different problem now - the original problem (Illegal instruction) has been fixed that is why i closed the issue - plz open a new issue if you have another problem in the future

those last errors are about missing gstreamer plugins - i found that some are split out into 'extras' packages on fedora - i was able to get past these plugin errors by installing two more packages:
- gstreamer1-plugins-bad-freeworld  <-- RTMP support
- gstreamer1-plugins-good-extras <-- JACK support
  
  su -c 'dnf install gstreamer1-plugins-bad-freeworld gstreamer1-plugins-good-extras'

sry again that i can not support fedora very well - i try things out in a VM now and then for fedora and opensuse but some features of gstreamer are expected not to work in a VM so i can not assume that any errors i see will be problems for real hardware - so thank you for reporting these problems

**Comment by bidzapfc** [comment]
First one I did have, Second one was missing. I have ran it successfully now, thanks
